kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: expense
  #these labels are deployment related labels.
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
#below is pod definition
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:{{ .Values.deployment.imageVersion }} # Please use your own image here. lingadevops/mysql:v1.0    